### ISSUE TITLE
beatsaber messed up with new update

### ISSUE THREAD

**Issue by Themonts8007** [Assistant/ModAssistant#369] opened 2021-07-26 03:27 UTC
my mod assistant is working nor my beatsaber after the new update can some one help me.

**Comment by LordNecton** [comment] 2021-07-26 03:44
Yours and everybodys is messed up...Have to wait for a update to Mod Assistant

**Comment by Melopod** [comment] 2021-07-26 04:35
ModAssistant requires no updates.
Mods have simply not been updated for the newest version of the game. Please be patient

**Comment by lolPants** [comment] 2021-07-26 09:48
Duplicate of #367

**Closed by lolPants** 2021-07-26 09:48 UTC
