### ISSUE TITLE
BSIPA doesn't really update

### ISSUE THREAD

**Issue by ericmccullough** [Assistant/ModAssistant#260] opened 2020-10-24 11:08 UTC
When I run ModAssistant (1.1.15), it shows BSIPA installed version 4.0.5 and the latest version 4.1.3.  I click the Install or Update button.  After it is done, they are the both 4.1.3.  I quit and restart ModAssistant and BSIPA is back to 4.0.5.  All the other updated mods stay at the latest version.

**Comment by Rickers2004** [comment] 2020-10-24 12:47
I had this same problem, I had to uninstall and reinstall Beatsaber to fix it, but the mods are still held in pending. I’ve started this (pending mods) issue recently on the page.

**Comment by lolPants** [comment] 2020-10-24 20:16
dupe of #258

**Closed by lolPants** 2020-10-24 20:16 UTC

**Comment by ericmccullough** [comment] 2020-10-25 15:04
I checked the IPA.exe version in the Beat Saber folder.  It is 4.1.3.

**Comment by ericmccullough** [comment] 2020-10-25 16:21
Manually ran the ipa.exe at a cmd prompt.
Ran ModAssistant.  
BSIPA is the latest version.
There were some exceptions in the .\Beat Saber\Logs\_latest.log related to version number and something else.
Those are gone now.
Maybe the issue belongs to BSIPA.
