### ISSUE TITLE
Mod assistant shows 1.12.2 mods, installs them, but they don't show up in Beat Saber

### ISSUE THREAD

**Issue by mchety** [Assistant/ModAssistant#261] opened 2020-10-24 19:32 UTC
When mod assistant opens it shows that it is on game version 1.12.2, and all mods show up, but when the game runs it doesn't show any of the mods. When I close the game and re-open mod assistant BSIPA is in red, so I update it, restart the game, and the mods still don't work, and every time I restart mod assistant BSIPA is in red and the mods won't work.

**Comment by lolPants** [comment] 2020-10-24 20:16
dupe of #258

**Closed by lolPants** 2020-10-24 20:16 UTC
